### ISSUE TITLE
can't use images

### ISSUE THREAD

**Issue by CypYouOnline** [vivmagarwal/strapi-plugin-custom-api-builder#7]
Hello, if i use images in content type, the result of the request to custom-api is a 500 error (internal server error).
PS : in the logs of strapi, the error is no such column t0.member_images

Full error :
> SqliteError: select distinct `t0`.`id`, `t0`.`member_name`, `t0`.`member_images`, `t1`.`family_id` from `family_members` as `t0` left join `family_members_family_links` as `t1` on `t0`.`id` = `t1`.`family_member_id` where (`t1`.`family_id` in (1)) - no such column: t0.member_images
    at Database.prepare (C:\Users\User\Documents\strapi-test\node_modules\better-sqlite3\lib\methods\wrappers.js:5:21)
    at Client_BetterSQLite3._query (C:\Users\User\Documents\strapi-test\node_modules\knex\lib\dialects\better-sqlite3\index.js:30:34)
    at executeQuery (C:\Users\User\Documents\strapi-test\node_modules\knex\lib\execution\internal\query-executioner.js:37:17)
    at Client_BetterSQLite3.query (C:\Users\User\Documents\strapi-test\node_modules\knex\lib\client.js:146:12)
    at Runner.query (C:\Users\User\Documents\strapi-test\node_modules\knex\lib\execution\runner.js:130:36)
    at ensureConnectionCallback (C:\Users\User\Documents\strapi-test\node_modules\knex\lib\execution\internal\ensure-connection-callback.js:13:17)
    at Runner.ensureConnection (C:\Users\User\Documents\strapi-test\node_modules\knex\lib\execution\runner.js:307:20)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Runner.run (C:\Users\User\Documents\strapi-test\node_modules\knex\lib\execution\runner.js:30:19)
    at async Object.execute (C:\Users\User\Documents\strapi-test\node_modules\@strapi\database\lib\query\query-builder.js:390:22)

**Comment by vivmagarwal** [comment]
Breaking changes: https://github.com/vivmagarwal/strapi-plugin-custom-api-builder/pull/11

**Comment by lakshmansha** [comment]
@vivmagarwal, we still face same issue.

Currently using the 1.0.4 version.
